### ISSUE TITLE
Use `ComplexEnergyState` in `STM._create_seed_graphs`

### ISSUE THREAD

**Issue by spflueger** [ComPWA/expertsystem#172] opened 2020-08-06 13:37 UTC
Instead of working with the nested dicts internally use `Particle` and `ComplexQuantumState` as graph properties. Since the `__eq__` operation between those classes (as compared to the nested dicts) can also be used to remove or simplify `CompareGraphElementPropertiesFunctor`.

**Comment by redeboer** [comment] 2020-08-06 14:09
Duplicate of #143

**Closed by redeboer** 2020-08-06 14:09 UTC
Labels: 🔨 Maintenance
